---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-boilerplate-golang
  labels:
    svc: svc-boilerplate-golang
    tier: backend
  namespace: finance-stag
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: svc-boilerplate-golang
      tier: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        svc: svc-boilerplate-golang
        tier: backend
    spec:
      imagePullSecrets:
        - name: gcr-uii-key
      containers:
        - name: svc-boilerplate-golang
          image: asia.gcr.io/uii-cloud-project/finance/backend/svc-boilerplate-golang:stag
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 1m
              memory: 32Mi
            limits:
              memory: 32Mi
          env:
            - name: DB_DRIVERNAME
              value: "mysql"
            - name: DB_USERNAME
              value: "default"
            - name: DB_PASSWORD
              value: "default"
            - name: DB_HOST
              value: "dbstaging.bsi.io"
            - name: DB_PORT
              value: "6033"
            - name: DB_NAME
              value: "boilerplate"
            - name: ORACLE_DB_DRIVERNAME
              value: "godror"
            - name: ORACLE_DB_USERNAME
              value: "keubank"
            - name: ORACLE_DB_PASSWORD
              value: "testing#"
            - name: ORACLE_DB_HOST
              value: "10.30.21.17"
            - name: ORACLE_DB_PORT
              value: "1521"
            - name: ORACLE_DB_SERVICE_NAME
              value: "transdb1"
            - name: PORT
              value: "80"
            - name: ENV
              value: "staging"
            - name: GIN_MODE
              value: "release"
          ports:
            - name: http-api
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-boilerplate-golang
  labels:
    svc: svc-boilerplate-golang
    tier: backend
  namespace: finance-stag
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  svc-boilerplate-golang-mapping
      prefix: /v1/finance/boilerplate
      rewrite: /public/api/v1
      service: svc-boilerplate-golang.finance-stag
      timeout_ms: 180000
spec:
  selector:
    svc: svc-boilerplate-golang
    tier: backend
  ports:
    - name: http
      port: 80
      targetPort: http-api
      protocol: TCP
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    svc: svc-boilerplate-golang
    tier: backend
  name: svc-boilerplate-golang
  namespace: finance-stag
spec:
  maxReplicas: 5
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: svc-boilerplate-golang
  metrics:
    - resource:
        name: memory
        target:
          averageUtilization: 50
          type: Utilization
      type: Resource
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: svc-boilerplate-golang
